// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220606163819_AddSeed")]
    partial class AddSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Core.Entities.CarCategoryEntity.CarCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("CarCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "A"
                        },
                        new
                        {
                            Id = 2,
                            Name = "B"
                        },
                        new
                        {
                            Id = 3,
                            Name = "C"
                        },
                        new
                        {
                            Id = 4,
                            Name = "D"
                        });
                });

            modelBuilder.Entity("Core.Entities.CarEntity.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<float>("LoadCapacity")
                        .HasColumnType("real");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TechnicalPassport")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Vin")
                        .HasMaxLength(17)
                        .IsUnicode(false)
                        .HasColumnType("varchar(17)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Color = "Blue",
                            CreationDate = new DateTimeOffset(new DateTime(2016, 7, 1, 14, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            IsVerified = true,
                            LoadCapacity = 681.4366f,
                            Model = "Ford,F350 Super Duty Crew Cab, Pickup",
                            RegistrationNumber = "ACNMRYCQNM1TY5GABM82",
                            TechnicalPassport = "3BNFTLGAH7N5ZXHCOAO2",
                            UserId = "2c2ce64f-34ca-4d7c-a10f-5e670b4c837c",
                            Vin = "19S1RJ24YCVQ8YO7T"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            Color = "Grey",
                            CreationDate = new DateTimeOffset(new DateTime(2016, 7, 2, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            IsVerified = true,
                            LoadCapacity = 970.34515f,
                            Model = "Ford,F250 Super Duty Super Cab, Pickup",
                            RegistrationNumber = "FYVU0N4M1X6LBADNRTW8",
                            TechnicalPassport = "C8AA8OJNGHIKEJLBX7QV",
                            UserId = "04e37cf3-407b-4f11-8856-33864cae582d",
                            Vin = "XEP4XNBK1CLTW7NKL"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Color = "Blue",
                            CreationDate = new DateTimeOffset(new DateTime(2016, 7, 1, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            IsVerified = true,
                            LoadCapacity = 545.48376f,
                            Model = "Jeep,Wrangler Unlimited, SUV",
                            RegistrationNumber = "JEL7RP2QK209TAWL4RVC",
                            TechnicalPassport = "WG6YKNDNCMFRHDEZ3X5Y",
                            UserId = "5a8f1618-d068-4d18-959b-ddaa1d93764c",
                            Vin = "G9LJ2WRYGK84828NM"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Color = "Grey",
                            CreationDate = new DateTimeOffset(new DateTime(2016, 7, 2, 14, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            IsVerified = true,
                            LoadCapacity = 916.468f,
                            Model = "Ford,F350 Super Duty Crew Cab, Pickup",
                            RegistrationNumber = "YN9SGWWI7MX320XD0KHV",
                            TechnicalPassport = "D5UIC4BRGA0NTGHLCRM0",
                            UserId = "04e37cf3-407b-4f11-8856-33864cae582d",
                            Vin = "9YB162A9LKUJ0TTQG"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Color = "Black",
                            CreationDate = new DateTimeOffset(new DateTime(2016, 7, 1, 17, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            IsVerified = true,
                            LoadCapacity = 978.31647f,
                            Model = "Jeep,Wrangler, SUV",
                            RegistrationNumber = "WLA9LIC19YG0XWW7AX9G",
                            TechnicalPassport = "6PGTAGOSLAAGPECC1SLJ",
                            UserId = "35414efd-16a4-449e-b2a8-9770bf43b698",
                            Vin = "BLDI3WWJ5EAOV64HZ"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Color = "White",
                            CreationDate = new DateTimeOffset(new DateTime(2016, 7, 5, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            IsVerified = true,
                            LoadCapacity = 608.53046f,
                            Model = "Ford,F350 Super Duty Super Cab, Pickup",
                            RegistrationNumber = "YOZBIJJ6ICPHYDUFSDSV",
                            TechnicalPassport = "25W51I58JSFQESCXD7KD",
                            UserId = "4f492e6b-6ca4-4e6a-9f4d-d5cfea92684d",
                            Vin = "N1L6XT916S1NDTSU9"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Color = "Red",
                            CreationDate = new DateTimeOffset(new DateTime(2016, 7, 4, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            IsVerified = true,
                            LoadCapacity = 606.1953f,
                            Model = "Nissan,Titan King Cab, Pickup",
                            RegistrationNumber = "PWZ351X1KSFJPIUKULCY",
                            TechnicalPassport = "HLNOQFJ5JXKZ0QX5L3SS",
                            UserId = "35414efd-16a4-449e-b2a8-9770bf43b698",
                            Vin = "MZM4NBX9FE1D439AC"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Color = "White",
                            CreationDate = new DateTimeOffset(new DateTime(2016, 7, 2, 16, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            IsVerified = true,
                            LoadCapacity = 547.0345f,
                            Model = "Ford,F350 Super Duty Super Cab, Pickup",
                            RegistrationNumber = "N7FIZKPZQSKMHZN2MS77",
                            TechnicalPassport = "AH6XNMTVAR2AKJYR6MNQ",
                            UserId = "35414efd-16a4-449e-b2a8-9770bf43b698",
                            Vin = "OLGQN4L8PXAK751IU"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Color = "White",
                            CreationDate = new DateTimeOffset(new DateTime(2016, 7, 3, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            IsVerified = true,
                            LoadCapacity = 834.0456f,
                            Model = "Nissan,Titan King Cab, Pickup",
                            RegistrationNumber = "ZQA1X1VV04HYZTKHXYP9",
                            TechnicalPassport = "2150ZCSQORAYFMPV6OP2",
                            UserId = "5a8f1618-d068-4d18-959b-ddaa1d93764c",
                            Vin = "PSSM7CG0XE2JLXLA2"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Color = "Green",
                            CreationDate = new DateTimeOffset(new DateTime(2016, 7, 2, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            IsVerified = true,
                            LoadCapacity = 852.68f,
                            Model = "Jeep,Wrangler Unlimited, SUV",
                            RegistrationNumber = "8TIJD4PB89MJPCC7D5G9",
                            TechnicalPassport = "NUWWV0R9VM3TK5GZA3T8",
                            UserId = "96878efe-2c05-4810-857a-5959ac7adc38",
                            Vin = "P4GZVK82OGSWJEXMN"
                        });
                });

            modelBuilder.Entity("Core.Entities.GoodCategoryEntity.GoodCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("GoodCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "FOOD"
                        },
                        new
                        {
                            Id = 2,
                            Name = "DRINKS"
                        },
                        new
                        {
                            Id = 3,
                            Name = "CLOTHING"
                        },
                        new
                        {
                            Id = 4,
                            Name = "FOOTWEAR"
                        },
                        new
                        {
                            Id = 5,
                            Name = "HYGIENE PRODUCTS"
                        },
                        new
                        {
                            Id = 6,
                            Name = "CAMOUFLAGE"
                        },
                        new
                        {
                            Id = 7,
                            Name = "MEDICINES"
                        });
                });

            modelBuilder.Entity("Core.Entities.OfferEntity.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatorRoleId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ExpirationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("GoodCategoryId")
                        .HasColumnType("int");

                    b.Property<float>("GoodsWeight")
                        .HasColumnType("real");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<string>("OfferCreatorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("OfferPointId")
                        .HasColumnType("int");

                    b.Property<int?>("RelatedTripId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CreatorRoleId");

                    b.HasIndex("GoodCategoryId");

                    b.HasIndex("OfferCreatorId");

                    b.HasIndex("OfferPointId");

                    b.HasIndex("RelatedTripId");

                    b.ToTable("Offers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTimeOffset(new DateTime(2022, 6, 27, 7, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatorRoleId = 1,
                            Description = "Sauer - HettingerPersevering SCSI Garden communities platforms engineer Canada hybrid Movies, Electronics & Garden Borders Lead calculate deposit Representative Shoes, Baby & Computers mint green back-end Intranet Portugal Configurable.",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 7, 6, 14, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            GoodCategoryId = 6,
                            GoodsWeight = 468.3591f,
                            IsClosed = false,
                            OfferCreatorId = "96878efe-2c05-4810-857a-5959ac7adc38",
                            OfferPointId = 1,
                            StartDate = new DateTimeOffset(new DateTime(2022, 7, 5, 7, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTimeOffset(new DateTime(2022, 6, 29, 6, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatorRoleId = 1,
                            Description = "Rolfson IncIB Auto Loan Account Electronics & Garden Consultant Avon standardization Frozen regional Creative European Unit of Account 17(E.U.A.-17) product utilisation overriding open architecture Valleys white throughput Congo Colorado Tajikistan Metal e-tailers Product Springs PCI digital User-centric Texas Canyon.",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 7, 6, 14, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            GoodCategoryId = 4,
                            GoodsWeight = 581.84503f,
                            IsClosed = false,
                            OfferCreatorId = "04e37cf3-407b-4f11-8856-33864cae582d",
                            OfferPointId = 2,
                            StartDate = new DateTimeOffset(new DateTime(2022, 7, 5, 5, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTimeOffset(new DateTime(2022, 6, 23, 18, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatorRoleId = 1,
                            Description = "D'Amore - KesslerSwitchable transparent multi-byte recontextualize Sleek Rubber Hat overriding Frozen Tools & Baby firewall Lithuania transmitting.",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 7, 10, 21, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            GoodCategoryId = 3,
                            GoodsWeight = 525.07806f,
                            IsClosed = false,
                            OfferCreatorId = "7896e42d-9afd-4525-90fd-53acafa00775",
                            OfferPointId = 3,
                            StartDate = new DateTimeOffset(new DateTime(2022, 7, 5, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTimeOffset(new DateTime(2022, 6, 24, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatorRoleId = 1,
                            Description = "Will GroupTasty Granite Shoes Associate syndicate Cambridgeshire Track Intelligent Soft Cheese bricks-and-clicks protocol Strategist Sleek Granite Bike override green Wooden Awesome Managed Gorgeous Granite Shoes Plastic distributed.",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 7, 8, 19, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            GoodCategoryId = 4,
                            GoodsWeight = 418.11533f,
                            IsClosed = false,
                            OfferCreatorId = "2c2ce64f-34ca-4d7c-a10f-5e670b4c837c",
                            OfferPointId = 4,
                            StartDate = new DateTimeOffset(new DateTime(2022, 7, 3, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTimeOffset(new DateTime(2022, 6, 21, 5, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatorRoleId = 2,
                            Description = "Blick - KeeblerPrincipal Accounts circuit Graphical User Interface open-source connect Director Canyon Switchable payment Investment Account Unbranded Extensions.",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 7, 9, 18, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            GoodCategoryId = 1,
                            GoodsWeight = 547.27167f,
                            IsClosed = false,
                            OfferCreatorId = "5a8f1618-d068-4d18-959b-ddaa1d93764c",
                            OfferPointId = 5,
                            StartDate = new DateTimeOffset(new DateTime(2022, 7, 4, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTimeOffset(new DateTime(2022, 6, 24, 5, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatorRoleId = 2,
                            Description = "Dooley - HermistonTasty Frozen Sausages back-end virtual Glens Markets Licensed Cotton Fish Michigan JBOD scalable Credit Card Account auxiliary application synergy navigating Lebanese Pound payment Seychelles Rupee invoice Wooden Fork Danish Krone Rue Investment Account Avon frame.",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 7, 6, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            GoodCategoryId = 6,
                            GoodsWeight = 418.5481f,
                            IsClosed = false,
                            OfferCreatorId = "4f492e6b-6ca4-4e6a-9f4d-d5cfea92684d",
                            OfferPointId = 6,
                            StartDate = new DateTimeOffset(new DateTime(2022, 7, 1, 7, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTimeOffset(new DateTime(2022, 6, 23, 17, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatorRoleId = 2,
                            Description = "Parker, Koepp and LubowitzBrazilian Real deposit synthesizing Accountability tan redefine Locks Automotive deliverables Incredible Generic Cotton Pants Unions Barbados Frozen back-end Trinidad and Tobago Personal Loan Account world-class viral Bedfordshire Village sexy groupware SDD.",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 7, 7, 19, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            GoodCategoryId = 4,
                            GoodsWeight = 261.3997f,
                            IsClosed = false,
                            OfferCreatorId = "4f492e6b-6ca4-4e6a-9f4d-d5cfea92684d",
                            OfferPointId = 7,
                            StartDate = new DateTimeOffset(new DateTime(2022, 7, 4, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTimeOffset(new DateTime(2022, 6, 27, 5, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatorRoleId = 2,
                            Description = "Stiedemann and SonsAwesome Street Awesome aggregate Rhode Island mindshare transmitting Books & Movies Checking Account green deposit Belarussian Ruble background payment vortals Quality Frozen syndicate deliverables Beauty, Health & Home firewall online calculating Gorgeous Plastic Soap Beauty, Games & Industrial definition.",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 7, 10, 21, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            GoodCategoryId = 2,
                            GoodsWeight = 557.63684f,
                            IsClosed = false,
                            OfferCreatorId = "5a8f1618-d068-4d18-959b-ddaa1d93764c",
                            OfferPointId = 8,
                            StartDate = new DateTimeOffset(new DateTime(2022, 7, 5, 7, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTimeOffset(new DateTime(2022, 6, 24, 21, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatorRoleId = 2,
                            Description = "Kuvalis LLCSleek Delaware parse Locks Auto Loan Account Integration Profit-focused Ergonomic Refined Plastic Table Shores Rubber Plastic Identity Practical microchip Berkshire yellow Buckinghamshire microchip generate Credit Card Account Liaison panel Generic Manager Intelligent Cotton Pants blockchains Industrial & Computers.",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 7, 9, 20, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            GoodCategoryId = 6,
                            GoodsWeight = 366.45535f,
                            IsClosed = false,
                            OfferCreatorId = "4f492e6b-6ca4-4e6a-9f4d-d5cfea92684d",
                            OfferPointId = 9,
                            StartDate = new DateTimeOffset(new DateTime(2022, 7, 1, 5, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTimeOffset(new DateTime(2022, 6, 21, 18, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatorRoleId = 2,
                            Description = "Green - CassinGeneric Cotton Branch Auto Loan Account human-resource Borders Gorgeous Frozen Pizza Lithuanian Litas copy yellow Berkshire withdrawal iterate.",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 7, 9, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            GoodCategoryId = 7,
                            GoodsWeight = 710.1935f,
                            IsClosed = false,
                            OfferCreatorId = "4f492e6b-6ca4-4e6a-9f4d-d5cfea92684d",
                            OfferPointId = 10,
                            StartDate = new DateTimeOffset(new DateTime(2022, 7, 1, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 11,
                            CreationDate = new DateTimeOffset(new DateTime(2022, 6, 21, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatorRoleId = 1,
                            Description = "Altenwerth and Sonsoverriding Accountability Kwacha Tenge generating bottom-line Tennessee Metrics Handcrafted Soft Gloves Credit Card Account.",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 7, 9, 17, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            GoodCategoryId = 1,
                            GoodsWeight = 93.85981f,
                            IsClosed = false,
                            OfferCreatorId = "35414efd-16a4-449e-b2a8-9770bf43b698",
                            OfferPointId = 11,
                            StartDate = new DateTimeOffset(new DateTime(2022, 7, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 12,
                            CreationDate = new DateTimeOffset(new DateTime(2022, 6, 25, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatorRoleId = 1,
                            Description = "Powlowski - BlockAvon Generic Soft Computer Washington Rustic synthesizing Gorgeous Steel Keyboard Home Loan Account asynchronous embrace Licensed customized Metal middleware Intranet Licensed plug-and-play multi-byte THX synthesize Personal Loan Account policy deposit Kids Practical Frozen Pants ubiquitous.",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 7, 10, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            GoodCategoryId = 5,
                            GoodsWeight = 371.23605f,
                            IsClosed = false,
                            OfferCreatorId = "04e37cf3-407b-4f11-8856-33864cae582d",
                            OfferPointId = 12,
                            StartDate = new DateTimeOffset(new DateTime(2022, 7, 2, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 13,
                            CreationDate = new DateTimeOffset(new DateTime(2022, 6, 23, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatorRoleId = 1,
                            Description = "Raynor and SonsPlastic Handcrafted Rubber Pants Moroccan Dirham Sleek Rubber Bike Orchestrator 24/7 GB Practical Supervisor Groves Sports, Movies & Games protocol Electronics SMTP Maine bluetooth invoice reboot payment Response magnetic leading-edge Personal Loan Account Research Legacy UIC-Franc Netherlands best-of-breed Passage.",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 7, 8, 17, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            GoodCategoryId = 4,
                            GoodsWeight = 944.4043f,
                            IsClosed = false,
                            OfferCreatorId = "96878efe-2c05-4810-857a-5959ac7adc38",
                            OfferPointId = 13,
                            StartDate = new DateTimeOffset(new DateTime(2022, 7, 4, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 14,
                            CreationDate = new DateTimeOffset(new DateTime(2022, 6, 28, 14, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatorRoleId = 1,
                            Description = "Considine, Flatley and Littlescale Oklahoma interface Regional morph transmit wireless GB Sleek Cotton Shoes Handcrafted Wooden Hat matrix synthesizing mint green optical revolutionary complexity Factors Personal Loan Account Cocos (Keeling) Islands Montana Baby, Sports & Health open system Auto Loan Account.",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 7, 8, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            GoodCategoryId = 7,
                            GoodsWeight = 81.458534f,
                            IsClosed = false,
                            OfferCreatorId = "04e37cf3-407b-4f11-8856-33864cae582d",
                            OfferPointId = 14,
                            StartDate = new DateTimeOffset(new DateTime(2022, 7, 3, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 15,
                            CreationDate = new DateTimeOffset(new DateTime(2022, 6, 20, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatorRoleId = 2,
                            Description = "Ebert IncADP array deposit Fresh productize RAM payment Product Engineer RSS Small Concrete Shoes Credit Card Account Usability AI holistic utilize Cotton Applications bypassing Run.",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 7, 8, 22, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            GoodCategoryId = 4,
                            GoodsWeight = 495.10312f,
                            IsClosed = false,
                            OfferCreatorId = "2c2ce64f-34ca-4d7c-a10f-5e670b4c837c",
                            OfferPointId = 15,
                            StartDate = new DateTimeOffset(new DateTime(2022, 7, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 16,
                            CreationDate = new DateTimeOffset(new DateTime(2022, 6, 26, 7, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatorRoleId = 2,
                            Description = "Turcotte - Handuser-centric Intelligent Soft Chair Decentralized Kids, Outdoors & Shoes withdrawal Guadeloupe Japan reboot convergence Licensed Steel Fish web services Stravenue Ports payment dedicated monitor optical mindshare Liechtenstein optical Customizable Bermuda Practical Tennessee National.",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 7, 6, 21, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            GoodCategoryId = 2,
                            GoodsWeight = 3.8011658f,
                            IsClosed = false,
                            OfferCreatorId = "5a8f1618-d068-4d18-959b-ddaa1d93764c",
                            OfferPointId = 16,
                            StartDate = new DateTimeOffset(new DateTime(2022, 7, 3, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 17,
                            CreationDate = new DateTimeOffset(new DateTime(2022, 6, 25, 14, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatorRoleId = 2,
                            Description = "Friesen IncGorgeous Auto Loan Account invoice Buckinghamshire Technician Directives Faroe Islands action-items matrix Licensed reboot Extended Movies & Electronics Cotton efficient port Gorgeous Granite Gloves bluetooth one-to-one facilitate Borders haptic open-source eyeballs Gorgeous Wooden Mouse Shoes & Games compressing New Mexico 24/365 Fields.",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 7, 7, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            GoodCategoryId = 4,
                            GoodsWeight = 232.47063f,
                            IsClosed = false,
                            OfferCreatorId = "7896e42d-9afd-4525-90fd-53acafa00775",
                            OfferPointId = 17,
                            StartDate = new DateTimeOffset(new DateTime(2022, 7, 1, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 18,
                            CreationDate = new DateTimeOffset(new DateTime(2022, 6, 29, 17, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatorRoleId = 2,
                            Description = "Torp - SatterfieldTugrik e-enable Executive supply-chains Fresh purple North Dakota backing up invoice Ergonomic Wooden Towels methodology methodologies Handcrafted Soft Soap deposit Iowa Greens Dynamic Savings Account Strategist Cotton.",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 7, 7, 19, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            GoodCategoryId = 3,
                            GoodsWeight = 983.3381f,
                            IsClosed = false,
                            OfferCreatorId = "7896e42d-9afd-4525-90fd-53acafa00775",
                            OfferPointId = 18,
                            StartDate = new DateTimeOffset(new DateTime(2022, 7, 4, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 19,
                            CreationDate = new DateTimeOffset(new DateTime(2022, 6, 27, 7, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatorRoleId = 1,
                            Description = "Pacocha, Hoeger and Connconnect Associate alarm China Awesome Concrete Bike Cameroon Liaison hacking Granite Investor deposit California repurpose Product.",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 7, 5, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            GoodCategoryId = 2,
                            GoodsWeight = 886.9942f,
                            IsClosed = false,
                            OfferCreatorId = "04e37cf3-407b-4f11-8856-33864cae582d",
                            OfferPointId = 19,
                            StartDate = new DateTimeOffset(new DateTime(2022, 7, 5, 7, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 20,
                            CreationDate = new DateTimeOffset(new DateTime(2022, 6, 21, 18, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatorRoleId = 1,
                            Description = "Hagenes LLCCorporate withdrawal Gorgeous Investor Computers & Baby capacity solid state New Zealand regional real-time Forint Division Beauty, Clothing & Outdoors optical.",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 7, 7, 15, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            GoodCategoryId = 7,
                            GoodsWeight = 715.99677f,
                            IsClosed = false,
                            OfferCreatorId = "2c2ce64f-34ca-4d7c-a10f-5e670b4c837c",
                            OfferPointId = 20,
                            StartDate = new DateTimeOffset(new DateTime(2022, 7, 4, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Core.Entities.PointEntity.Point", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Settlement")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TripId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("Points");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "місто Острог, Рівненська область, вулиця Східна",
                            Latitude = 50.328792,
                            Longitude = 26.527293,
                            Order = 0,
                            Region = "Рівненська область",
                            Settlement = "Острог"
                        },
                        new
                        {
                            Id = 2,
                            Address = "місто Шпанів, Рівненська область, вулиця Вереснева",
                            Latitude = 50.663542,
                            Longitude = 26.257569,
                            Order = 0,
                            Region = " Рівненська область",
                            Settlement = "Шпанів"
                        },
                        new
                        {
                            Id = 3,
                            Address = "місто Луцьк, Волинська область, вулиця Хрещата",
                            Latitude = 50.723970999999999,
                            Longitude = 25.386282000000001,
                            Order = 0,
                            Region = "Волинська область",
                            Settlement = "Луцьк"
                        },
                        new
                        {
                            Id = 4,
                            Address = "місто Дніпро, Дніпропетровська область, вулиця Юрія Савченко",
                            Latitude = 48.462322270000001,
                            Longitude = 35.021573400000001,
                            Order = 0,
                            Region = "Дніпропетровська область",
                            Settlement = "Дніпро"
                        },
                        new
                        {
                            Id = 5,
                            Address = "місто Нікольське, Донецька область, вулиця Пушкіна",
                            Latitude = 47.200732350000003,
                            Longitude = 37.3148804,
                            Order = 0,
                            Region = "Донецька область",
                            Settlement = "Нікольське"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Макаровка, Донецька область",
                            Latitude = 47.779212000000001,
                            Longitude = 36.801640999999996,
                            Order = 0,
                            Region = "Донецька область",
                            Settlement = "Макаровка"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Гаврилівка, Харківська область, вулиця Коцюбинського",
                            Latitude = 49.672877999999997,
                            Longitude = 35.660035000000001,
                            Order = 0,
                            Region = "Харківська область",
                            Settlement = "Дніпро"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Ульянівка, Харківська область",
                            Latitude = 49.371445999999999,
                            Longitude = 35.513638,
                            Order = 0,
                            Region = "Харківська область",
                            Settlement = "Ульянівка"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Новодонецьк, Донецька область, вулиця Благовісна",
                            Latitude = 48.633740000000003,
                            Longitude = 36.980499999999999,
                            Order = 0,
                            Region = "Донецька область",
                            Settlement = "Новодонецьк"
                        },
                        new
                        {
                            Id = 10,
                            Address = "місто Дніпро, Дніпропетровська область, вулиця Юрія Савченко",
                            Latitude = 48.460256999999999,
                            Longitude = 35.018729,
                            Order = 0,
                            Region = "Дніпропетровська область",
                            Settlement = "Дніпро"
                        },
                        new
                        {
                            Id = 11,
                            Address = "місто Львів, Львівська область, просп. Вячеслава Черновола, 11",
                            Latitude = 49.846894900000002,
                            Longitude = 4.0253360999999996,
                            Order = 0,
                            Region = "Львівська область",
                            Settlement = "Львів"
                        },
                        new
                        {
                            Id = 12,
                            Address = "місто Ужгород, Закарпатская область, вулиця Шишкіна, 1",
                            Latitude = 48.610622999999997,
                            Longitude = 22.317772999999999,
                            Order = 0,
                            Region = "Закарпатская область",
                            Settlement = "Ужгород"
                        },
                        new
                        {
                            Id = 13,
                            Address = "Маків, Хмельницька  область, провулок Прорізний",
                            Latitude = 48.784157,
                            Longitude = 26.702999999999999,
                            Order = 0,
                            Region = "Хмельницька  область",
                            Settlement = "Маків"
                        },
                        new
                        {
                            Id = 14,
                            Address = "місто Вінниця, Вінницька область, вулиця Братславська",
                            Latitude = 49.232585,
                            Longitude = 28.494243999999998,
                            Order = 0,
                            Region = "Вінницька область",
                            Settlement = "Вінниця"
                        },
                        new
                        {
                            Id = 15,
                            Address = "місто Миколаїв, Миколаївська область, вулиця Слов'янська",
                            Latitude = 47.032940848000003,
                            Longitude = 32.007182749999998,
                            Order = 0,
                            Region = "Миколаївська область",
                            Settlement = "Миколаїв"
                        },
                        new
                        {
                            Id = 16,
                            Address = "Центральний пайон, місто Миколаїв, Миколаївська область, вулиця Дачна",
                            Latitude = 47.044604,
                            Longitude = 32.030366999999998,
                            Order = 0,
                            Region = "Миколаївська область",
                            Settlement = "Миколаїв"
                        },
                        new
                        {
                            Id = 17,
                            Address = "Бобринець, Кіровоградська  область, вулиця Орджонікідзе",
                            Latitude = 48.061315,
                            Longitude = 32.158811,
                            Order = 0,
                            Region = "Кіровоградська  область",
                            Settlement = "Бобринець"
                        },
                        new
                        {
                            Id = 18,
                            Address = "Горбово, Чернігівська область, 16311",
                            Latitude = 51.45984,
                            Longitude = 31.561633,
                            Order = 0,
                            Region = "Чернігівська область",
                            Settlement = "Горбово"
                        },
                        new
                        {
                            Id = 19,
                            Address = "місто Біла церква, Київська область, вулиця Кірова",
                            Latitude = 49.807687086999998,
                            Longitude = 30.1144958,
                            Order = 0,
                            Region = "Київська область",
                            Settlement = "Біла церква"
                        },
                        new
                        {
                            Id = 20,
                            Address = "місто Житомир, Житомирська область, Богунський район",
                            Latitude = 50.259729999999998,
                            Longitude = 28.649229999999999,
                            Order = 0,
                            Region = "Житомирська область",
                            Settlement = "Житомир"
                        });
                });

            modelBuilder.Entity("Core.Entities.RatingEntity.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstimatorUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Mark")
                        .HasColumnType("int");

                    b.Property<string>("RatedUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("RatingDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstimatorUserId");

                    b.HasIndex("RatedUserId");

                    b.HasIndex("TripId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("Core.Entities.RefreshTokenEntity.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Core.Entities.ReportEntity.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportedUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReporterUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("ReportingDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReportedUserId");

                    b.HasIndex("ReporterUserId");

                    b.HasIndex("TripId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Core.Entities.RoleEntity.OfferRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OfferRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "SENDER"
                        },
                        new
                        {
                            Id = 2,
                            Name = "RECIPIENT"
                        });
                });

            modelBuilder.Entity("Core.Entities.TripEntity.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpirationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnded")
                        .HasColumnType("bit");

                    b.Property<float>("LoadCapacity")
                        .HasColumnType("real");

                    b.Property<int>("MaxRouteDeviationKm")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TransportationCarId")
                        .HasColumnType("int");

                    b.Property<string>("TripCreatorId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TransportationCarId");

                    b.HasIndex("TripCreatorId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "7139c955-57ae-4546-85d9-7541330c93d4",
                            ConcurrencyStamp = "7139c955-57ae-4546-85d9-7541330c93d4",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "9da2a5aa-4cef-4223-be7c-c66e05ba11a2",
                            ConcurrencyStamp = "9da2a5aa-4cef-4223-be7c-c66e05ba11a2",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "7979dc73-10ea-4de9-ac5b-4ba4b127c37b",
                            ConcurrencyStamp = "7979dc73-10ea-4de9-ac5b-4ba4b127c37b",
                            Name = "Logist",
                            NormalizedName = "LOGIST"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "04e37cf3-407b-4f11-8856-33864cae582d",
                            RoleId = "7139c955-57ae-4546-85d9-7541330c93d4"
                        },
                        new
                        {
                            UserId = "4f492e6b-6ca4-4e6a-9f4d-d5cfea92684d",
                            RoleId = "7139c955-57ae-4546-85d9-7541330c93d4"
                        },
                        new
                        {
                            UserId = "7896e42d-9afd-4525-90fd-53acafa00775",
                            RoleId = "7139c955-57ae-4546-85d9-7541330c93d4"
                        },
                        new
                        {
                            UserId = "5a8f1618-d068-4d18-959b-ddaa1d93764c",
                            RoleId = "7139c955-57ae-4546-85d9-7541330c93d4"
                        },
                        new
                        {
                            UserId = "2c2ce64f-34ca-4d7c-a10f-5e670b4c837c",
                            RoleId = "7139c955-57ae-4546-85d9-7541330c93d4"
                        },
                        new
                        {
                            UserId = "72a85512-0abf-44dc-ada6-9ad6e015787e",
                            RoleId = "7979dc73-10ea-4de9-ac5b-4ba4b127c37b"
                        },
                        new
                        {
                            UserId = "96878efe-2c05-4810-857a-5959ac7adc38",
                            RoleId = "7139c955-57ae-4546-85d9-7541330c93d4"
                        },
                        new
                        {
                            UserId = "35414efd-16a4-449e-b2a8-9770bf43b698",
                            RoleId = "7139c955-57ae-4546-85d9-7541330c93d4"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Core.Entities.UserEntity.User", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("ConfirmationEmailToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ConfirmationEmailTokenExpirationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("HasCar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Rating")
                        .HasColumnType("real");

                    b.Property<DateTimeOffset>("RegistrationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("User");

                    b.HasData(
                        new
                        {
                            Id = "04e37cf3-407b-4f11-8856-33864cae582d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4e468c37-d381-4d6c-a780-09e41d008ca4",
                            Email = "chorrny228@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "CHORRNY228@GMAIL.COM",
                            NormalizedUserName = "CHORRNY228@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEAgo4M3cy2NyK6x+KM6Jrxh7NLlT6rgiv94nNB5/1ijsulKy2e5atnr1NB04U9j9eA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3d55dcf4-151d-4738-9e6a-24d8b332f5b5",
                            TwoFactorEnabled = false,
                            UserName = "chorrny228@gmail.com",
                            HasCar = false,
                            Name = "Vadym",
                            RegistrationDate = new DateTimeOffset(new DateTime(2022, 6, 6, 16, 38, 18, 447, DateTimeKind.Unspecified).AddTicks(6649), new TimeSpan(0, 0, 0, 0, 0)),
                            Surname = "Chorrny"
                        },
                        new
                        {
                            Id = "4f492e6b-6ca4-4e6a-9f4d-d5cfea92684d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6dc31a8e-7a02-4a1d-bb33-46a4fa70dc98",
                            Email = "oppaiarchmaster@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "OPPAIARCHMASTER@GMAIL.COM",
                            NormalizedUserName = "OPPAIARCHMASTER@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEEcQhfKzZfuEwUMDT0uvJAt06o7cXakPDVwQVQc9AbAoz50vt5C/uLspmtLr0C/Yxw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fda6ad79-893e-4a78-8731-e6837e9d2943",
                            TwoFactorEnabled = false,
                            UserName = "oppaiarchmaster@gmail.com",
                            HasCar = false,
                            Name = "Vlad",
                            RegistrationDate = new DateTimeOffset(new DateTime(2022, 6, 6, 16, 38, 18, 447, DateTimeKind.Unspecified).AddTicks(8191), new TimeSpan(0, 0, 0, 0, 0)),
                            Surname = "Sievostyanov"
                        },
                        new
                        {
                            Id = "72a85512-0abf-44dc-ada6-9ad6e015787e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "274c3b4f-f543-4116-b69f-05efd2459da9",
                            Email = "andrewchepeliuk@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ANDREWCHEPELIUK@GMAIL.COM",
                            NormalizedUserName = "ANDREWCHEPELIUK@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEHDrxLPYkp6eSOvloAgzRCsiKBWZHoj2bEGpkha0zXYjYHK5sb+5egqB/mFQ0Dwexw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "61de1f84-e68f-4591-8d35-daedf84c7e55",
                            TwoFactorEnabled = false,
                            UserName = "andrewchepeliuk@gmail.com",
                            HasCar = false,
                            Name = "Andrii",
                            RegistrationDate = new DateTimeOffset(new DateTime(2022, 6, 6, 16, 38, 18, 447, DateTimeKind.Unspecified).AddTicks(8248), new TimeSpan(0, 0, 0, 0, 0)),
                            Surname = "Chepeliuk"
                        },
                        new
                        {
                            Id = "5a8f1618-d068-4d18-959b-ddaa1d93764c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b7936243-0c30-4e23-b316-c2a4ce5f664b",
                            Email = "mapourse@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MAPOURSE@GMAIL.COM",
                            NormalizedUserName = "MAPOURSE@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEHBhUtFq7lMeEEdPKg63oicow0dZ+JEAHiBWYDVetiZrD2XSJj/gbdkkTfW9uqBtkw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "23dea56c-7e29-4c40-a2a2-ec2d9dbccfe9",
                            TwoFactorEnabled = false,
                            UserName = "mapourse@gmail.com",
                            HasCar = false,
                            Name = "Maryna",
                            RegistrationDate = new DateTimeOffset(new DateTime(2022, 6, 6, 16, 38, 18, 447, DateTimeKind.Unspecified).AddTicks(8261), new TimeSpan(0, 0, 0, 0, 0)),
                            Surname = "Kernychna"
                        },
                        new
                        {
                            Id = "96878efe-2c05-4810-857a-5959ac7adc38",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a5f3ecf0-48e2-4ce2-8755-e7b560e819c4",
                            Email = "yevhen.pasichnyk@oa.edu.ua",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "YEVHEN.PASICHNYK@OA.EDU.UA",
                            NormalizedUserName = "YEVHEN.PASICHNYK@OA.EDU.UA",
                            PasswordHash = "AQAAAAEAACcQAAAAEKixe5TTaGMbmT4GhOsiRJfry9YKMMNy+9v/0xYuoediRKt1fo+oOLTrk130f1OrDg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "30f89562-9292-4c16-a139-e0b05886469c",
                            TwoFactorEnabled = false,
                            UserName = "yevhen.pasichnyk@oa.edu.ua",
                            HasCar = false,
                            Name = "Eugen",
                            RegistrationDate = new DateTimeOffset(new DateTime(2022, 6, 6, 16, 38, 18, 447, DateTimeKind.Unspecified).AddTicks(8279), new TimeSpan(0, 0, 0, 0, 0)),
                            Surname = "Pasichnyk"
                        },
                        new
                        {
                            Id = "7896e42d-9afd-4525-90fd-53acafa00775",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5c108036-b374-46bc-879e-bf28f3b2eda7",
                            Email = "pashunskyi@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PASHUNSKYI@GMAIL.COM",
                            NormalizedUserName = "PASHUNSKYI@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEDVyZMok9cwM2AX81Ar8lAKbZpG0Ar0Vn+2xT47Ocyo6pih/D2lwjjtiwNpsRzkSiw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "177b0b9f-631a-454e-9548-ec12e55f1d1a",
                            TwoFactorEnabled = false,
                            UserName = "pashunskyi@gmail.com",
                            HasCar = false,
                            Name = "Volodya",
                            RegistrationDate = new DateTimeOffset(new DateTime(2022, 6, 6, 16, 38, 18, 447, DateTimeKind.Unspecified).AddTicks(8291), new TimeSpan(0, 0, 0, 0, 0)),
                            Surname = "Pashunskyi"
                        },
                        new
                        {
                            Id = "2c2ce64f-34ca-4d7c-a10f-5e670b4c837c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a328a278-c4e4-42f1-ba3c-89d19f737f94",
                            Email = "antonina.loboda@oa.edu.ua",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ANTONINA.LOBODA@OA.EDU.UA",
                            NormalizedUserName = "ANTONINA.LOBODA@OA.EDU.UA",
                            PasswordHash = "AQAAAAEAACcQAAAAEFJj5VUdlMKRJv4TU3ItC0ybHlz+7XzygWZDHTSVt2ianUUS6IWMtIlj24KWEqIkrA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b1f06859-fa2b-44d5-a66b-f0dfbc88610d",
                            TwoFactorEnabled = false,
                            UserName = "antonina.loboda@oa.edu.ua",
                            HasCar = false,
                            Name = "Antonina",
                            RegistrationDate = new DateTimeOffset(new DateTime(2022, 6, 6, 16, 38, 18, 447, DateTimeKind.Unspecified).AddTicks(8302), new TimeSpan(0, 0, 0, 0, 0)),
                            Surname = "Loboda"
                        },
                        new
                        {
                            Id = "35414efd-16a4-449e-b2a8-9770bf43b698",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "757f4c5c-7ddc-4d25-b075-8a4c91641e3f",
                            Email = "sergeyeremenko@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SERGEYEREMENKO@GMAIL.COM",
                            NormalizedUserName = "SERGEYEREMENKO@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEEj6B6X5gouykM9Uo4xlqvmrlfZOAhBv3jYFzEbPOwEokcugVFyM1TAXrAUzOAPijg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bdca2d0b-181c-4fa0-b66f-f6950b6d8ae5",
                            TwoFactorEnabled = false,
                            UserName = "sergeyeremenko@gmail.com",
                            HasCar = false,
                            Name = "Sergey",
                            RegistrationDate = new DateTimeOffset(new DateTime(2022, 6, 6, 16, 38, 18, 447, DateTimeKind.Unspecified).AddTicks(8317), new TimeSpan(0, 0, 0, 0, 0)),
                            Surname = "Eremenko"
                        });
                });

            modelBuilder.Entity("Core.Entities.CarEntity.Car", b =>
                {
                    b.HasOne("Core.Entities.CarCategoryEntity.CarCategory", "Category")
                        .WithMany("Cars")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.UserEntity.User", "User")
                        .WithMany("Cars")
                        .HasForeignKey("UserId");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.OfferEntity.Offer", b =>
                {
                    b.HasOne("Core.Entities.RoleEntity.OfferRole", "OfferRole")
                        .WithMany("Offers")
                        .HasForeignKey("CreatorRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.GoodCategoryEntity.GoodCategory", "GoodCategory")
                        .WithMany("Offers")
                        .HasForeignKey("GoodCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.UserEntity.User", "User")
                        .WithMany("Offers")
                        .HasForeignKey("OfferCreatorId");

                    b.HasOne("Core.Entities.PointEntity.Point", "Point")
                        .WithMany("Offers")
                        .HasForeignKey("OfferPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.TripEntity.Trip", "Trip")
                        .WithMany("Offers")
                        .HasForeignKey("RelatedTripId");

                    b.Navigation("GoodCategory");

                    b.Navigation("OfferRole");

                    b.Navigation("Point");

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.PointEntity.Point", b =>
                {
                    b.HasOne("Core.Entities.TripEntity.Trip", "Trip")
                        .WithMany("Points")
                        .HasForeignKey("TripId");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Core.Entities.RatingEntity.Rating", b =>
                {
                    b.HasOne("Core.Entities.UserEntity.User", "EstimatorUser")
                        .WithMany("EstimatorRatings")
                        .HasForeignKey("EstimatorUserId");

                    b.HasOne("Core.Entities.UserEntity.User", "RatedUser")
                        .WithMany("RatedRatings")
                        .HasForeignKey("RatedUserId");

                    b.HasOne("Core.Entities.TripEntity.Trip", "Trip")
                        .WithMany("Ratings")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstimatorUser");

                    b.Navigation("RatedUser");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Core.Entities.RefreshTokenEntity.RefreshToken", b =>
                {
                    b.HasOne("Core.Entities.UserEntity.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.ReportEntity.Report", b =>
                {
                    b.HasOne("Core.Entities.UserEntity.User", "ReportedUser")
                        .WithMany("ViolationReports")
                        .HasForeignKey("ReportedUserId");

                    b.HasOne("Core.Entities.UserEntity.User", "ReporterUser")
                        .WithMany("ReporterReports")
                        .HasForeignKey("ReporterUserId");

                    b.HasOne("Core.Entities.TripEntity.Trip", "Trip")
                        .WithMany("Reports")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportedUser");

                    b.Navigation("ReporterUser");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Core.Entities.TripEntity.Trip", b =>
                {
                    b.HasOne("Core.Entities.CarEntity.Car", "Car")
                        .WithMany("Trips")
                        .HasForeignKey("TransportationCarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.UserEntity.User", "User")
                        .WithMany("Trips")
                        .HasForeignKey("TripCreatorId");

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.CarCategoryEntity.CarCategory", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("Core.Entities.CarEntity.Car", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("Core.Entities.GoodCategoryEntity.GoodCategory", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("Core.Entities.PointEntity.Point", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("Core.Entities.RoleEntity.OfferRole", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("Core.Entities.TripEntity.Trip", b =>
                {
                    b.Navigation("Offers");

                    b.Navigation("Points");

                    b.Navigation("Ratings");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("Core.Entities.UserEntity.User", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("EstimatorRatings");

                    b.Navigation("Offers");

                    b.Navigation("RatedRatings");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ReporterReports");

                    b.Navigation("Trips");

                    b.Navigation("ViolationReports");
                });
#pragma warning restore 612, 618
        }
    }
}
