// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Core.Entities.CarCategoryEntity.CarCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("CarCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "A"
                        },
                        new
                        {
                            Id = 2,
                            Name = "B"
                        },
                        new
                        {
                            Id = 3,
                            Name = "C"
                        },
                        new
                        {
                            Id = 4,
                            Name = "D"
                        });
                });

            modelBuilder.Entity("Core.Entities.CarEntity.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<float>("LoadCapacity")
                        .HasColumnType("real");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TechnicalPassport")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Vin")
                        .HasMaxLength(17)
                        .IsUnicode(false)
                        .HasColumnType("varchar(17)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 4,
                            Color = "Жовтий",
                            CreationDate = new DateTimeOffset(new DateTime(2016, 5, 7, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            IsVerified = true,
                            LoadCapacity = 795.84216f,
                            Model = "V 814 E",
                            RegistrationNumber = "OT4QN9NLV8NYMO033001",
                            TechnicalPassport = "OQN2YPZUF7FO7ZE7IAEW",
                            UserId = "0a5942cf-ec42-40e8-b2ea-decda57825e1",
                            Vin = "HTRKW4U6YWTRIY52S"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Color = "Чорний",
                            CreationDate = new DateTimeOffset(new DateTime(2016, 4, 7, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            IsVerified = true,
                            LoadCapacity = 481.70877f,
                            Model = "E 714 U",
                            RegistrationNumber = "ZQM9SLTM3DT8UADSU099",
                            TechnicalPassport = "JUGHG1GIFMVPT0RUAU1K",
                            UserId = "97980051-7ac5-4fec-87fa-97b477272484",
                            Vin = "PEPPBRE6FRVF94A5T"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 4,
                            Color = "Синій",
                            CreationDate = new DateTimeOffset(new DateTime(2016, 5, 7, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            IsVerified = true,
                            LoadCapacity = 650.487f,
                            Model = "E 521 M",
                            RegistrationNumber = "3FTIJI0ZO4942SRQO497",
                            TechnicalPassport = "3TDRMK41AFT39WL9H8UN",
                            UserId = "4b06fdc7-5a2c-4a6c-a81a-ca62d0241362",
                            Vin = "7B008C1ZH6W9EA11W"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Color = "Жовтий",
                            CreationDate = new DateTimeOffset(new DateTime(2016, 2, 7, 17, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            IsVerified = true,
                            LoadCapacity = 418.05743f,
                            Model = "R 344 H",
                            RegistrationNumber = "5V57I8F9LSBM2RMCSZAY",
                            TechnicalPassport = "N6ZHA7FCVAF3X1U424JR",
                            UserId = "97980051-7ac5-4fec-87fa-97b477272484",
                            Vin = "BH2OZA9MKZEBMYWNW"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Color = "Сірий",
                            CreationDate = new DateTimeOffset(new DateTime(2016, 2, 7, 17, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            IsVerified = true,
                            LoadCapacity = 950.19006f,
                            Model = "K 382 I",
                            RegistrationNumber = "7P1WIANGJXQVHFM8528P",
                            TechnicalPassport = "GPLEV7E79YXIZ5UZXDRC",
                            UserId = "0a5942cf-ec42-40e8-b2ea-decda57825e1",
                            Vin = "UEW2E8A2N05LWI3N0"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Color = "Зелений",
                            CreationDate = new DateTimeOffset(new DateTime(2016, 4, 7, 18, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            IsVerified = true,
                            LoadCapacity = 935.2106f,
                            Model = "E 630 Z",
                            RegistrationNumber = "7WCKNARBVSWU6HST5X7A",
                            TechnicalPassport = "WCE9CVACGGHC9FP62ONR",
                            UserId = "0a5942cf-ec42-40e8-b2ea-decda57825e1",
                            Vin = "ASZNW58HQIZA2UH37"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Color = "Чорний",
                            CreationDate = new DateTimeOffset(new DateTime(2016, 5, 7, 16, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            IsVerified = true,
                            LoadCapacity = 558.55096f,
                            Model = "W 466 I",
                            RegistrationNumber = "KLRRLQGAFE82L9PZ44YQ",
                            TechnicalPassport = "YCYCVPZGVRHSVHF24DMQ",
                            UserId = "0a5942cf-ec42-40e8-b2ea-decda57825e1",
                            Vin = "KVURWTIRV9WOC7MFW"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Color = "Синій",
                            CreationDate = new DateTimeOffset(new DateTime(2016, 1, 7, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            IsVerified = true,
                            LoadCapacity = 472.74176f,
                            Model = "K 702 X",
                            RegistrationNumber = "F73UMUQI7HQS2I3S5Y3W",
                            TechnicalPassport = "7W747FPGPY9UWYEKSYVX",
                            UserId = "0a5942cf-ec42-40e8-b2ea-decda57825e1",
                            Vin = "O7MEJWT4M1ARPJZZM"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            Color = "Жовтий",
                            CreationDate = new DateTimeOffset(new DateTime(2016, 5, 7, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            IsVerified = true,
                            LoadCapacity = 647.64215f,
                            Model = "V 323 F",
                            RegistrationNumber = "VW43IZ726RG70HTWTNKC",
                            TechnicalPassport = "8K49VKTBOSUXGZQHFSA4",
                            UserId = "0a5942cf-ec42-40e8-b2ea-decda57825e1",
                            Vin = "3Z8CZHTACM8WZBSU8"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Color = "Чорний",
                            CreationDate = new DateTimeOffset(new DateTime(2016, 4, 7, 17, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            IsVerified = true,
                            LoadCapacity = 593.0873f,
                            Model = "K 468 Y",
                            RegistrationNumber = "IR0RBG0CGY9G41JLBIDF",
                            TechnicalPassport = "7PJ0EPLKCXJKO2PLYQHU",
                            UserId = "0a5942cf-ec42-40e8-b2ea-decda57825e1",
                            Vin = "RXQVOSPCVC0YPT70C"
                        });
                });

            modelBuilder.Entity("Core.Entities.GoodCategoryEntity.GoodCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("GoodCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "FOOD"
                        },
                        new
                        {
                            Id = 2,
                            Name = "DRINKS"
                        },
                        new
                        {
                            Id = 3,
                            Name = "CLOTHING"
                        },
                        new
                        {
                            Id = 4,
                            Name = "FOOTWEAR"
                        },
                        new
                        {
                            Id = 5,
                            Name = "HYGIENE PRODUCTS"
                        },
                        new
                        {
                            Id = 6,
                            Name = "CAMOUFLAGE"
                        },
                        new
                        {
                            Id = 7,
                            Name = "MEDICINES"
                        });
                });

            modelBuilder.Entity("Core.Entities.OfferEntity.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatorRoleId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ExpirationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("GoodCategoryId")
                        .HasColumnType("int");

                    b.Property<float>("GoodsWeight")
                        .HasColumnType("real");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<string>("OfferCreatorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("OfferPointId")
                        .HasColumnType("int");

                    b.Property<int?>("RelatedTripId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CreatorRoleId");

                    b.HasIndex("GoodCategoryId");

                    b.HasIndex("OfferCreatorId");

                    b.HasIndex("OfferPointId");

                    b.HasIndex("RelatedTripId");

                    b.ToTable("Offers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatorRoleId = 1,
                            Description = "Oklahoma communities Usability AI Fantastic synthesize portal Trinidad and Tobago Intelligent Innovative Money Market Account Future Handcrafted Frozen Chicken Forward bypassing Swedish Krona Checking Account mobile program auxiliary India.",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 8, 7, 18, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            GoodCategoryId = 7,
                            GoodsWeight = 140.1205f,
                            IsClosed = false,
                            OfferCreatorId = "4177e658-5333-43cd-ac51-1260c26a64fe",
                            OfferPointId = 1,
                            StartDate = new DateTimeOffset(new DateTime(2022, 2, 7, 7, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatorRoleId = 1,
                            Description = "Savings Account Tasty Plastic Bacon Wooden zero administration tan logistical invoice Courts Bermuda Granite Kids & Shoes.",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 6, 7, 17, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            GoodCategoryId = 2,
                            GoodsWeight = 500.17395f,
                            IsClosed = false,
                            OfferCreatorId = "97980051-7ac5-4fec-87fa-97b477272484",
                            OfferPointId = 2,
                            StartDate = new DateTimeOffset(new DateTime(2022, 1, 7, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatorRoleId = 1,
                            Description = "microchip Web copy olive redundant Pre-emptive Idaho indexing product Alley JBOD Ergonomic Granite Pants Kansas Automotive & Beauty Toys & Tools Indian Rupee neural hardware adapter reboot Sleek Metal Tuna Oval Books driver hacking users Dynamic convergence Norwegian Krone.",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 9, 7, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            GoodCategoryId = 7,
                            GoodsWeight = 969.0529f,
                            IsClosed = false,
                            OfferCreatorId = "7c8da2cc-96e2-446d-9547-6315ea35ac28",
                            OfferPointId = 3,
                            StartDate = new DateTimeOffset(new DateTime(2022, 4, 7, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatorRoleId = 1,
                            Description = "Tenge deposit real-time alliance Money Market Account Markets Utah South Dakota user-centric Intuitive Shoes & Outdoors Belize revolutionary overriding EXE Inlet Borders Unbranded Monaco Handmade dynamic Common Handmade Cotton Pizza.",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 8, 7, 19, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            GoodCategoryId = 2,
                            GoodsWeight = 103.27014f,
                            IsClosed = false,
                            OfferCreatorId = "980dc472-9edd-4ec0-a9ec-fbf33bffa8d5",
                            OfferPointId = 4,
                            StartDate = new DateTimeOffset(new DateTime(2022, 5, 7, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatorRoleId = 2,
                            Description = "calculate Diverse Diverse supply-chains Station maroon Mobility Island withdrawal budgetary management Loaf View Credit Card Account Executive Assistant Electronics, Outdoors & Home demand-driven transition Switzerland backing up toolset web-enabled Metal Arkansas.",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 6, 7, 15, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            GoodCategoryId = 2,
                            GoodsWeight = 258.2349f,
                            IsClosed = false,
                            OfferCreatorId = "0445929e-685a-45af-93f2-2784891fe9c7",
                            OfferPointId = 5,
                            StartDate = new DateTimeOffset(new DateTime(2022, 2, 7, 6, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatorRoleId = 2,
                            Description = "Parkway Face to face Borders connect blue Extensions Gorgeous schemas mission-critical platforms Specialist Refined Granite Table application Cape Personal Loan Account Tasty.",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 8, 7, 16, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            GoodCategoryId = 3,
                            GoodsWeight = 787.09515f,
                            IsClosed = false,
                            OfferCreatorId = "ea711007-e129-4f5f-a3e3-769b4ea06a00",
                            OfferPointId = 6,
                            StartDate = new DateTimeOffset(new DateTime(2022, 2, 7, 7, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatorRoleId = 2,
                            Description = "Bosnia and Herzegovina models Lights optical Sweden Personal Loan Account Home & Tools networks Unbranded Steel Chair Practical Granite Computer Sleek Wooden Hat Fiji Dollar Grocery & Electronics hack Small Frozen Sausages Dynamic Associate Generic Granite Salad PNG installation.",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 10, 7, 14, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            GoodCategoryId = 3,
                            GoodsWeight = 507.2459f,
                            IsClosed = false,
                            OfferCreatorId = "ea711007-e129-4f5f-a3e3-769b4ea06a00",
                            OfferPointId = 7,
                            StartDate = new DateTimeOffset(new DateTime(2022, 3, 7, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatorRoleId = 2,
                            Description = "synergistic Liaison e-enable e-enable Rubber process improvement Movies, Music & Industrial Berkshire Awesome Frozen Mouse invoice Operations Frozen Streamlined SMS pixel Upgradable.",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 9, 7, 20, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            GoodCategoryId = 3,
                            GoodsWeight = 35.695515f,
                            IsClosed = false,
                            OfferCreatorId = "0445929e-685a-45af-93f2-2784891fe9c7",
                            OfferPointId = 8,
                            StartDate = new DateTimeOffset(new DateTime(2022, 4, 7, 6, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatorRoleId = 2,
                            Description = "Avenue interactive Knoll Architect compressing navigate Germany Mandatory incentivize Accountability index Incredible Cotton Pizza Unbranded Fresh Bike revolutionize Personal Loan Account Unbranded.",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 8, 7, 15, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            GoodCategoryId = 3,
                            GoodsWeight = 669.97394f,
                            IsClosed = false,
                            OfferCreatorId = "ea711007-e129-4f5f-a3e3-769b4ea06a00",
                            OfferPointId = 9,
                            StartDate = new DateTimeOffset(new DateTime(2022, 5, 7, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatorRoleId = 2,
                            Description = "Vista next generation Auto Loan Account Licensed Cotton Cheese Borders Tasty Frozen Mouse Forest Generic Rubber Salad Assurance Savings Account.",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 8, 7, 16, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            GoodCategoryId = 5,
                            GoodsWeight = 300.46283f,
                            IsClosed = false,
                            OfferCreatorId = "ea711007-e129-4f5f-a3e3-769b4ea06a00",
                            OfferPointId = 10,
                            StartDate = new DateTimeOffset(new DateTime(2022, 4, 7, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 11,
                            CreationDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatorRoleId = 1,
                            Description = "maximize scalable Awesome Wooden Chicken methodologies Rustic Cotton Salad Developer primary conglomeration interface Alaska California syndicate niches copying SDD cross-platform Checking Account Ridge.",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 10, 7, 22, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            GoodCategoryId = 5,
                            GoodsWeight = 917.5849f,
                            IsClosed = false,
                            OfferCreatorId = "4b06fdc7-5a2c-4a6c-a81a-ca62d0241362",
                            OfferPointId = 11,
                            StartDate = new DateTimeOffset(new DateTime(2022, 5, 7, 6, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 12,
                            CreationDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatorRoleId = 1,
                            Description = "flexibility Generic Granite Computer infomediaries Associate efficient Rustic Rubber Ball Clothing disintermediate Rubber Handmade payment protocol olive Tasty Fresh Car.",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 7, 7, 14, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            GoodCategoryId = 4,
                            GoodsWeight = 180.31082f,
                            IsClosed = false,
                            OfferCreatorId = "97980051-7ac5-4fec-87fa-97b477272484",
                            OfferPointId = 12,
                            StartDate = new DateTimeOffset(new DateTime(2022, 2, 7, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 13,
                            CreationDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatorRoleId = 1,
                            Description = "compressing installation relationships model Licensed Wooden Gloves Dynamic Codes specifically reserved for testing purposes transmitting Botswana PNG platforms Drive Practical Integration sensor programming firmware open-source.",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 5, 7, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            GoodCategoryId = 6,
                            GoodsWeight = 246.50653f,
                            IsClosed = false,
                            OfferCreatorId = "4177e658-5333-43cd-ac51-1260c26a64fe",
                            OfferPointId = 13,
                            StartDate = new DateTimeOffset(new DateTime(2022, 1, 7, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 14,
                            CreationDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatorRoleId = 1,
                            Description = "invoice RSS productize Roads back-end Unbranded Wooden Salad Mandatory SMS Brand withdrawal.",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 5, 7, 19, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            GoodCategoryId = 4,
                            GoodsWeight = 18.720966f,
                            IsClosed = false,
                            OfferCreatorId = "97980051-7ac5-4fec-87fa-97b477272484",
                            OfferPointId = 14,
                            StartDate = new DateTimeOffset(new DateTime(2022, 5, 7, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 15,
                            CreationDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatorRoleId = 2,
                            Description = "Metal hard drive Frozen white Infrastructure bifurcated connect enhance infomediaries clicks-and-mortar Savings Account Course navigate Tasty Frozen Computer Fundamental Electronics cross-platform implement Supervisor.",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 8, 7, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            GoodCategoryId = 7,
                            GoodsWeight = 191.82733f,
                            IsClosed = false,
                            OfferCreatorId = "980dc472-9edd-4ec0-a9ec-fbf33bffa8d5",
                            OfferPointId = 15,
                            StartDate = new DateTimeOffset(new DateTime(2022, 5, 7, 6, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 16,
                            CreationDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatorRoleId = 2,
                            Description = "payment Architect knowledge user mobile mission-critical input compress systemic throughput Granite.",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 5, 7, 19, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            GoodCategoryId = 3,
                            GoodsWeight = 255.86082f,
                            IsClosed = false,
                            OfferCreatorId = "0445929e-685a-45af-93f2-2784891fe9c7",
                            OfferPointId = 16,
                            StartDate = new DateTimeOffset(new DateTime(2022, 3, 7, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 17,
                            CreationDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatorRoleId = 2,
                            Description = "Flat hierarchy indexing Incredible Plastic Computer back up Manors Optional pixel context-sensitive reboot Clothing, Jewelery & Tools bandwidth reboot mobile Louisiana parse Unbranded Concrete Towels Strategist generate International Industrial Practical Cotton Keyboard Operative violet protocol Practical sky blue lavender Unbranded Granite.",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 10, 7, 19, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            GoodCategoryId = 6,
                            GoodsWeight = 601.0029f,
                            IsClosed = false,
                            OfferCreatorId = "7c8da2cc-96e2-446d-9547-6315ea35ac28",
                            OfferPointId = 17,
                            StartDate = new DateTimeOffset(new DateTime(2022, 3, 7, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 18,
                            CreationDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatorRoleId = 2,
                            Description = "disintermediate primary innovate Generic Knoll copying multi-byte Jersey hacking Handmade Cotton Towels Street optical Hungary Spur convergence Path Corporate Principal Solomon Islands Dollar Frozen hard drive leading edge synergy Rustic transmitting Avon Buckinghamshire Rand instruction set.",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 9, 7, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            GoodCategoryId = 3,
                            GoodsWeight = 202.54924f,
                            IsClosed = false,
                            OfferCreatorId = "7c8da2cc-96e2-446d-9547-6315ea35ac28",
                            OfferPointId = 18,
                            StartDate = new DateTimeOffset(new DateTime(2022, 4, 7, 5, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 19,
                            CreationDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatorRoleId = 1,
                            Description = "Profound synthesize RSS Port South Africa Awesome Concrete Towels Money Market Account Cambridgeshire Alabama partnerships violet Branding tan functionalities Awesome Frozen Tuna Gorgeous Nepalese Rupee Markets Industrial & Outdoors Investment Account Tasty Rubber Shirt Oregon e-services Avon Valleys Fields web-enabled Proactive.",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 8, 7, 17, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            GoodCategoryId = 3,
                            GoodsWeight = 775.0064f,
                            IsClosed = false,
                            OfferCreatorId = "97980051-7ac5-4fec-87fa-97b477272484",
                            OfferPointId = 19,
                            StartDate = new DateTimeOffset(new DateTime(2022, 3, 7, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 20,
                            CreationDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatorRoleId = 1,
                            Description = "TCP Tasty Steel Keyboard secured line New Jersey Triple-buffered Incredible Plastic Keyboard Dam Data auxiliary panel Intelligent Plastic Computer Soft Berkshire Seamless Singapore Dollar Future-proofed Avon Ergonomic Steel Soap Games hub optimize relationships.",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 6, 7, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            GoodCategoryId = 7,
                            GoodsWeight = 544.8283f,
                            IsClosed = false,
                            OfferCreatorId = "4b06fdc7-5a2c-4a6c-a81a-ca62d0241362",
                            OfferPointId = 20,
                            StartDate = new DateTimeOffset(new DateTime(2022, 5, 7, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Core.Entities.PointEntity.Point", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Settlement")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TripId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("Points");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "місто Остріг, Рівненська область, вулиця Східна",
                            Latitude = 50.328792,
                            Longitude = 26.527293,
                            Order = 0,
                            Region = "Рівненська область",
                            Settlement = "Острог"
                        },
                        new
                        {
                            Id = 2,
                            Address = "місто Шпанів, Рівненська область, вулиця Вереснева",
                            Latitude = 50.663542,
                            Longitude = 26.257569,
                            Order = 0,
                            Region = " Рівненська область",
                            Settlement = "Шпанів"
                        },
                        new
                        {
                            Id = 3,
                            Address = "місто Луцьк, Волинська область, вулиця Хрещата",
                            Latitude = 50.723970999999999,
                            Longitude = 25.386282000000001,
                            Order = 0,
                            Region = "Волинська область",
                            Settlement = "Луцьк"
                        },
                        new
                        {
                            Id = 4,
                            Address = "місто Дніпро, Дніпропетровська область, вулиця Юрія Савченко",
                            Latitude = 48.462322270000001,
                            Longitude = 35.021573400000001,
                            Order = 0,
                            Region = "Дніпропетровська область",
                            Settlement = "Дніпро"
                        },
                        new
                        {
                            Id = 5,
                            Address = "місто Нікольське, Донецька область, вулиця Пушкіна",
                            Latitude = 47.200732350000003,
                            Longitude = 37.3148804,
                            Order = 0,
                            Region = "Донецька область",
                            Settlement = "Нікольське"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Макаровка, Донецька область",
                            Latitude = 47.779212000000001,
                            Longitude = 36.801640999999996,
                            Order = 0,
                            Region = "Донецька область",
                            Settlement = "Макаровка"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Гаврилівка, Харківська область, вулиця Коцюбинського",
                            Latitude = 49.672877999999997,
                            Longitude = 35.660035000000001,
                            Order = 0,
                            Region = "Харківська область",
                            Settlement = "Дніпро"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Ульянівка, Харківська область",
                            Latitude = 49.371445999999999,
                            Longitude = 35.513638,
                            Order = 0,
                            Region = "Харківська область",
                            Settlement = "Ульянівка"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Новодонецьк, Донецька область, вулиця Благовісна",
                            Latitude = 48.633740000000003,
                            Longitude = 36.980499999999999,
                            Order = 0,
                            Region = "Донецька область",
                            Settlement = "Новодонецьк"
                        },
                        new
                        {
                            Id = 10,
                            Address = "місто Дніпро, Дніпропетровська область, вулиця Юрія Савченко",
                            Latitude = 48.460256999999999,
                            Longitude = 35.018729,
                            Order = 0,
                            Region = "Дніпропетровська область",
                            Settlement = "Дніпро"
                        },
                        new
                        {
                            Id = 11,
                            Address = "місто Львів, Львівська область, просп. Вячеслава Черновола, 11",
                            Latitude = 49.846894900000002,
                            Longitude = 4.0253360999999996,
                            Order = 0,
                            Region = "Львівська область",
                            Settlement = "Львів"
                        },
                        new
                        {
                            Id = 12,
                            Address = "місто Ужгород, Закарпатская область, вулиця Шишкіна, 1",
                            Latitude = 48.610622999999997,
                            Longitude = 22.317772999999999,
                            Order = 0,
                            Region = "Закарпатская область",
                            Settlement = "Ужгород"
                        },
                        new
                        {
                            Id = 13,
                            Address = "Маків, Хмельницька  область, провулок Прорізний",
                            Latitude = 48.784157,
                            Longitude = 26.702999999999999,
                            Order = 0,
                            Region = "Хмельницька  область",
                            Settlement = "Маків"
                        },
                        new
                        {
                            Id = 14,
                            Address = "місто Вінниця, Вінницька область, вулиця Братславська",
                            Latitude = 49.232585,
                            Longitude = 28.494243999999998,
                            Order = 0,
                            Region = "Вінницька область",
                            Settlement = "Вінниця"
                        },
                        new
                        {
                            Id = 15,
                            Address = "місто Миколаїв, Миколаївська область, вулиця Слов'янська",
                            Latitude = 47.032940848000003,
                            Longitude = 32.007182749999998,
                            Order = 0,
                            Region = "Миколаївська область",
                            Settlement = "Миколаїв"
                        },
                        new
                        {
                            Id = 16,
                            Address = "Центральний пайон, місто Миколаїв, Миколаївська область, вулиця Дачна",
                            Latitude = 47.044604,
                            Longitude = 32.030366999999998,
                            Order = 0,
                            Region = "Миколаївська область",
                            Settlement = "Миколаїв"
                        },
                        new
                        {
                            Id = 17,
                            Address = "Бобринець, Кіровоградська  область, вулиця Орджонікідзе",
                            Latitude = 48.061315,
                            Longitude = 32.158811,
                            Order = 0,
                            Region = "Кіровоградська  область",
                            Settlement = "Бобринець"
                        },
                        new
                        {
                            Id = 18,
                            Address = "Горбово, Чернігівська область, 16311",
                            Latitude = 51.45984,
                            Longitude = 31.561633,
                            Order = 0,
                            Region = "Чернігівська область",
                            Settlement = "Горбово"
                        },
                        new
                        {
                            Id = 19,
                            Address = "місто Біла церква, Київська область, вулиця Кірова",
                            Latitude = 49.807687086999998,
                            Longitude = 30.1144958,
                            Order = 0,
                            Region = "Київська область",
                            Settlement = "Біла церква"
                        },
                        new
                        {
                            Id = 20,
                            Address = "місто Житомир, Житомирська область, Богунський район",
                            Latitude = 50.259729999999998,
                            Longitude = 28.649229999999999,
                            Order = 0,
                            Region = "Житомирська область",
                            Settlement = "Житомир"
                        });
                });

            modelBuilder.Entity("Core.Entities.RatingEntity.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstimatorUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Mark")
                        .HasColumnType("int");

                    b.Property<string>("RatedUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("RatingDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstimatorUserId");

                    b.HasIndex("RatedUserId");

                    b.HasIndex("TripId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("Core.Entities.RefreshTokenEntity.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Core.Entities.ReportEntity.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportedUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReporterUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("ReportingDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReportedUserId");

                    b.HasIndex("ReporterUserId");

                    b.HasIndex("TripId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Core.Entities.RoleEntity.OfferRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "SENDER"
                        },
                        new
                        {
                            Id = 2,
                            Name = "RECIPIENT"
                        });
                });

            modelBuilder.Entity("Core.Entities.TripEntity.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpirationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnded")
                        .HasColumnType("bit");

                    b.Property<float>("LoadCapacity")
                        .HasColumnType("real");

                    b.Property<int>("MaxRouteDeviationKm")
                        .HasColumnType("int");

                    b.Property<int?>("PointId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TransportationCarId")
                        .HasColumnType("int");

                    b.Property<string>("TripCreatorId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PointId");

                    b.HasIndex("TransportationCarId");

                    b.HasIndex("TripCreatorId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "ebaf7f30-11ff-4f50-b6e5-bfa278f48b06",
                            ConcurrencyStamp = "ebaf7f30-11ff-4f50-b6e5-bfa278f48b06",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "0935268b-06a2-449c-8e4a-a9324c47f4b7",
                            ConcurrencyStamp = "0935268b-06a2-449c-8e4a-a9324c47f4b7",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "1f0a4268-5dcd-4d46-aa88-0d1784b8fa17",
                            ConcurrencyStamp = "1f0a4268-5dcd-4d46-aa88-0d1784b8fa17",
                            Name = "Logist",
                            NormalizedName = "LOGIST"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "97980051-7ac5-4fec-87fa-97b477272484",
                            RoleId = "ebaf7f30-11ff-4f50-b6e5-bfa278f48b06"
                        },
                        new
                        {
                            UserId = "ea711007-e129-4f5f-a3e3-769b4ea06a00",
                            RoleId = "ebaf7f30-11ff-4f50-b6e5-bfa278f48b06"
                        },
                        new
                        {
                            UserId = "7c8da2cc-96e2-446d-9547-6315ea35ac28",
                            RoleId = "ebaf7f30-11ff-4f50-b6e5-bfa278f48b06"
                        },
                        new
                        {
                            UserId = "0445929e-685a-45af-93f2-2784891fe9c7",
                            RoleId = "ebaf7f30-11ff-4f50-b6e5-bfa278f48b06"
                        },
                        new
                        {
                            UserId = "980dc472-9edd-4ec0-a9ec-fbf33bffa8d5",
                            RoleId = "ebaf7f30-11ff-4f50-b6e5-bfa278f48b06"
                        },
                        new
                        {
                            UserId = "4b06fdc7-5a2c-4a6c-a81a-ca62d0241362",
                            RoleId = "ebaf7f30-11ff-4f50-b6e5-bfa278f48b06"
                        },
                        new
                        {
                            UserId = "4177e658-5333-43cd-ac51-1260c26a64fe",
                            RoleId = "ebaf7f30-11ff-4f50-b6e5-bfa278f48b06"
                        },
                        new
                        {
                            UserId = "0a5942cf-ec42-40e8-b2ea-decda57825e1",
                            RoleId = "ebaf7f30-11ff-4f50-b6e5-bfa278f48b06"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Core.Entities.UserEntity.User", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<bool>("HasCar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Rating")
                        .HasColumnType("real");

                    b.Property<DateTimeOffset>("RegistrationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("User");

                    b.HasData(
                        new
                        {
                            Id = "97980051-7ac5-4fec-87fa-97b477272484",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "962d1e2e-63e9-4db7-a74c-1f24f3b931cb",
                            Email = "chorrny228@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "CHORRNY228@GMAIL.COM",
                            NormalizedUserName = "CHORRNY228@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEPkLW6J1XKNOZQvsFOpzfUYvK7cgrNHhhM8clt3befFOkqt3Nkem6BWk/UhFgMbvyw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fcfcf4d1-a7e2-4a02-b8d9-6dd921d91476",
                            TwoFactorEnabled = false,
                            UserName = "chorrny228@gmail.com",
                            HasCar = false,
                            Name = "Vadym",
                            RegistrationDate = new DateTimeOffset(new DateTime(2022, 5, 15, 12, 37, 23, 458, DateTimeKind.Unspecified).AddTicks(9138), new TimeSpan(0, 0, 0, 0, 0)),
                            Surname = "Chorrny"
                        },
                        new
                        {
                            Id = "ea711007-e129-4f5f-a3e3-769b4ea06a00",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6d29fd2c-b76f-47ca-a69b-9a1297e2fe98",
                            Email = "oppaiarchmaster@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "OPPAIARCHMASTER@GMAIL.COM",
                            NormalizedUserName = "OPPAIARCHMASTER@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEMD3c9OtaWmk9eX9GlZ8eB9DVlTyUOsVvKV8WAxWWmyTbm1Qr5OuTOrZ8Gegy0XbHg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c287935d-0948-46bf-a0a7-6558060f337f",
                            TwoFactorEnabled = false,
                            UserName = "oppaiarchmaster@gmail.com",
                            HasCar = false,
                            Name = "Vlad",
                            RegistrationDate = new DateTimeOffset(new DateTime(2022, 5, 15, 12, 37, 23, 459, DateTimeKind.Unspecified).AddTicks(1818), new TimeSpan(0, 0, 0, 0, 0)),
                            Surname = "Sevastyanov"
                        },
                        new
                        {
                            Id = "4b06fdc7-5a2c-4a6c-a81a-ca62d0241362",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4ed2d9d8-2f26-4b61-a5f0-47ba1b4a78e3",
                            Email = "andrewchepeliuk@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ANDREWCHEPELIUK@GMAIL.COM",
                            NormalizedUserName = "ANDREWCHEPELIUK@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEJ/QbtNcY52m+04PplyiBLCuVnI+uEIWL0liyeEWhdVNG9x8vSm9+4pkh0bhu9XONg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cb88bbc9-e006-4d34-b1ad-460f78605fd0",
                            TwoFactorEnabled = false,
                            UserName = "andrewchepeliuk@gmail.com",
                            HasCar = false,
                            Name = "Andrii",
                            RegistrationDate = new DateTimeOffset(new DateTime(2022, 5, 15, 12, 37, 23, 459, DateTimeKind.Unspecified).AddTicks(1939), new TimeSpan(0, 0, 0, 0, 0)),
                            Surname = "Chepeliuk"
                        },
                        new
                        {
                            Id = "0445929e-685a-45af-93f2-2784891fe9c7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6c700de1-c9e5-4cc8-8c9c-4a4deadd97f3",
                            Email = "marynakernychna@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MARYNAKERNYCHNA@GMAIL.COM",
                            NormalizedUserName = "MARYNAKERNYCHNA@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEA40Hq8i2MZtKVsRIpx1AhH54gd61+us8+fjrvA7yTzsjjK0X1l+wlOBv+BGv3BvUQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a020f6af-440f-4b26-9ae4-f3567ce89c61",
                            TwoFactorEnabled = false,
                            UserName = "marynakernychna@gmail.com",
                            HasCar = false,
                            Name = "Maryna",
                            RegistrationDate = new DateTimeOffset(new DateTime(2022, 5, 15, 12, 37, 23, 459, DateTimeKind.Unspecified).AddTicks(1967), new TimeSpan(0, 0, 0, 0, 0)),
                            Surname = "Kernychna"
                        },
                        new
                        {
                            Id = "4177e658-5333-43cd-ac51-1260c26a64fe",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c00a3fe4-8d1e-466d-8c4a-66de55eb9321",
                            Email = "yevhen.pasichnyk@oa.edu.ua",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "YEVHEN.PASICHNYK@OA.EDU.UA",
                            NormalizedUserName = "YEVHEN.PASICHNYK@OA.EDU.UA",
                            PasswordHash = "AQAAAAEAACcQAAAAEAyo5LWCZ7MuYkpcs4tfCGCZZQbpMmhdrKpmtSiZJKnhcqnHYSMRtSpTveHKXUFeZA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "09ffeda2-9631-4e7e-8ecd-5800b0d8e0d2",
                            TwoFactorEnabled = false,
                            UserName = "yevhen.pasichnyk@oa.edu.ua",
                            HasCar = false,
                            Name = "Eugen",
                            RegistrationDate = new DateTimeOffset(new DateTime(2022, 5, 15, 12, 37, 23, 459, DateTimeKind.Unspecified).AddTicks(1997), new TimeSpan(0, 0, 0, 0, 0)),
                            Surname = "Pasichnyk"
                        },
                        new
                        {
                            Id = "7c8da2cc-96e2-446d-9547-6315ea35ac28",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "50eedf75-6d3d-4f19-a341-34afb049b34d",
                            Email = "pashunskyi@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PASHUNSKYI@GMAIL.COM",
                            NormalizedUserName = "PASHUNSKYI@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEMh2vqZLWDHryZveg+kZ6KAo3JHlWp7iYwyPvLr/eP5lD4ipF3ByGScR/VcBHFlHFg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9e16374a-ab96-4ce7-a21f-7f106ef49cf5",
                            TwoFactorEnabled = false,
                            UserName = "pashunskyi@gmail.com",
                            HasCar = false,
                            Name = "Volodya",
                            RegistrationDate = new DateTimeOffset(new DateTime(2022, 5, 15, 12, 37, 23, 459, DateTimeKind.Unspecified).AddTicks(2023), new TimeSpan(0, 0, 0, 0, 0)),
                            Surname = "Pashunskyi"
                        },
                        new
                        {
                            Id = "980dc472-9edd-4ec0-a9ec-fbf33bffa8d5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "03ab3d15-e008-4a1c-aa06-a78caf6f21f5",
                            Email = "antonina.loboda@oa.edu.ua",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ANTONINA.LOBODA@OA.EDU.UA",
                            NormalizedUserName = "ANTONINA.LOBODA@OA.EDU.UA",
                            PasswordHash = "AQAAAAEAACcQAAAAEFT3u+VAn4OYKRYcaE3YACBK6b721O2aEz+azaK2bQX0k6e43QOwSVxH5+c3kyopUA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8b0d8da5-b914-4ed5-b517-76cb51fce50e",
                            TwoFactorEnabled = false,
                            UserName = "antonina.loboda@oa.edu.ua",
                            HasCar = false,
                            Name = "Antonina",
                            RegistrationDate = new DateTimeOffset(new DateTime(2022, 5, 15, 12, 37, 23, 459, DateTimeKind.Unspecified).AddTicks(2047), new TimeSpan(0, 0, 0, 0, 0)),
                            Surname = "Loboda"
                        },
                        new
                        {
                            Id = "0a5942cf-ec42-40e8-b2ea-decda57825e1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "acfb5d19-a2a9-4ae7-b882-4bb28de1a84c",
                            Email = "sergeyeremenko@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SERGEYEREMENKO@GMAIL.COM",
                            NormalizedUserName = "SERGEYEREMENKO@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEG4FK13VJsFG71oPwyvZ2CzsB+CqwVgLvIpOdI6TIUYFogLUohx+m8Ceyr5o71sAig==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "506de7bd-9d12-4c1f-b840-a8f2fb949ed1",
                            TwoFactorEnabled = false,
                            UserName = "sergeyeremenko@gmail.com",
                            HasCar = false,
                            Name = "Sergey",
                            RegistrationDate = new DateTimeOffset(new DateTime(2022, 5, 15, 12, 37, 23, 459, DateTimeKind.Unspecified).AddTicks(2074), new TimeSpan(0, 0, 0, 0, 0)),
                            Surname = "Eremenko"
                        });
                });

            modelBuilder.Entity("Core.Entities.CarEntity.Car", b =>
                {
                    b.HasOne("Core.Entities.CarCategoryEntity.CarCategory", "Category")
                        .WithMany("Cars")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.UserEntity.User", "User")
                        .WithMany("Cars")
                        .HasForeignKey("UserId");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.OfferEntity.Offer", b =>
                {
                    b.HasOne("Core.Entities.RoleEntity.OfferRole", "OfferRole")
                        .WithMany("Offers")
                        .HasForeignKey("CreatorRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.GoodCategoryEntity.GoodCategory", "GoodCategory")
                        .WithMany("Offers")
                        .HasForeignKey("GoodCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.UserEntity.User", "User")
                        .WithMany("Offers")
                        .HasForeignKey("OfferCreatorId");

                    b.HasOne("Core.Entities.PointEntity.Point", "Point")
                        .WithMany("Offers")
                        .HasForeignKey("OfferPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.TripEntity.Trip", "Trip")
                        .WithMany("Offers")
                        .HasForeignKey("RelatedTripId");

                    b.Navigation("GoodCategory");

                    b.Navigation("OfferRole");

                    b.Navigation("Point");

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.PointEntity.Point", b =>
                {
                    b.HasOne("Core.Entities.TripEntity.Trip", "Trip")
                        .WithMany("Points")
                        .HasForeignKey("TripId");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Core.Entities.RatingEntity.Rating", b =>
                {
                    b.HasOne("Core.Entities.UserEntity.User", "EstimatorUser")
                        .WithMany("EstimatorRatings")
                        .HasForeignKey("EstimatorUserId");

                    b.HasOne("Core.Entities.UserEntity.User", "RatedUser")
                        .WithMany("RatedRatings")
                        .HasForeignKey("RatedUserId");

                    b.HasOne("Core.Entities.TripEntity.Trip", "Trip")
                        .WithMany("Ratings")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstimatorUser");

                    b.Navigation("RatedUser");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Core.Entities.RefreshTokenEntity.RefreshToken", b =>
                {
                    b.HasOne("Core.Entities.UserEntity.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.ReportEntity.Report", b =>
                {
                    b.HasOne("Core.Entities.UserEntity.User", "ReportedUser")
                        .WithMany("ViolationReports")
                        .HasForeignKey("ReportedUserId");

                    b.HasOne("Core.Entities.UserEntity.User", "ReporterUser")
                        .WithMany("ReporterReports")
                        .HasForeignKey("ReporterUserId");

                    b.HasOne("Core.Entities.TripEntity.Trip", "Trip")
                        .WithMany("Reports")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportedUser");

                    b.Navigation("ReporterUser");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Core.Entities.TripEntity.Trip", b =>
                {
                    b.HasOne("Core.Entities.PointEntity.Point", null)
                        .WithMany("Trips")
                        .HasForeignKey("PointId");

                    b.HasOne("Core.Entities.CarEntity.Car", "Car")
                        .WithMany("Trips")
                        .HasForeignKey("TransportationCarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.UserEntity.User", "User")
                        .WithMany("Trips")
                        .HasForeignKey("TripCreatorId");

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.CarCategoryEntity.CarCategory", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("Core.Entities.CarEntity.Car", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("Core.Entities.GoodCategoryEntity.GoodCategory", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("Core.Entities.PointEntity.Point", b =>
                {
                    b.Navigation("Offers");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("Core.Entities.RoleEntity.OfferRole", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("Core.Entities.TripEntity.Trip", b =>
                {
                    b.Navigation("Offers");

                    b.Navigation("Points");

                    b.Navigation("Ratings");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("Core.Entities.UserEntity.User", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("EstimatorRatings");

                    b.Navigation("Offers");

                    b.Navigation("RatedRatings");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ReporterReports");

                    b.Navigation("Trips");

                    b.Navigation("ViolationReports");
                });
#pragma warning restore 612, 618
        }
    }
}
